//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.6413
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.CompactFramework.Design.Data generó automáticamente este código fuente, versión=2.0.50727.6413.
// 
namespace OA_Movil.ServicioPrueba {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioOASoap", Namespace="http://200.56.177.82/ServicioOA/")]
    public partial class ServicioOA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ServicioOA() {
            this.Url = "http://200.56.117.82/ServicioOA/Serviciooa.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://200.56.177.82/ServicioOA/IniciarVisita", RequestNamespace="http://200.56.177.82/ServicioOA/", ResponseNamespace="http://200.56.177.82/ServicioOA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet IniciarVisita(string pCliente) {
            object[] results = this.Invoke("IniciarVisita", new object[] {
                        pCliente});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIniciarVisita(string pCliente, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IniciarVisita", new object[] {
                        pCliente}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndIniciarVisita(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://200.56.177.82/ServicioOA/FinalizarVisita", RequestNamespace="http://200.56.177.82/ServicioOA/", ResponseNamespace="http://200.56.177.82/ServicioOA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool FinalizarVisita(string pVisita) {
            object[] results = this.Invoke("FinalizarVisita", new object[] {
                        pVisita});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFinalizarVisita(string pVisita, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FinalizarVisita", new object[] {
                        pVisita}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndFinalizarVisita(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://200.56.177.82/ServicioOA/EliminarProductoConteo", RequestNamespace="http://200.56.177.82/ServicioOA/", ResponseNamespace="http://200.56.177.82/ServicioOA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarProductoConteo(string pVisita, string pClave) {
            object[] results = this.Invoke("EliminarProductoConteo", new object[] {
                        pVisita,
                        pClave});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEliminarProductoConteo(string pVisita, string pClave, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EliminarProductoConteo", new object[] {
                        pVisita,
                        pClave}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndEliminarProductoConteo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://200.56.177.82/ServicioOA/ObtenerRestantesConteo", RequestNamespace="http://200.56.177.82/ServicioOA/", ResponseNamespace="http://200.56.177.82/ServicioOA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerRestantesConteo(string pVisita) {
            object[] results = this.Invoke("ObtenerRestantesConteo", new object[] {
                        pVisita});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginObtenerRestantesConteo(string pVisita, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerRestantesConteo", new object[] {
                        pVisita}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndObtenerRestantesConteo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://200.56.177.82/ServicioOA/ObtenerDiferenciasConteo", RequestNamespace="http://200.56.177.82/ServicioOA/", ResponseNamespace="http://200.56.177.82/ServicioOA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerDiferenciasConteo(string pVisita) {
            object[] results = this.Invoke("ObtenerDiferenciasConteo", new object[] {
                        pVisita});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginObtenerDiferenciasConteo(string pVisita, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerDiferenciasConteo", new object[] {
                        pVisita}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndObtenerDiferenciasConteo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://200.56.177.82/ServicioOA/ObtenerPreFactura", RequestNamespace="http://200.56.177.82/ServicioOA/", ResponseNamespace="http://200.56.177.82/ServicioOA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerPreFactura(string pVisita) {
            object[] results = this.Invoke("ObtenerPreFactura", new object[] {
                        pVisita});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginObtenerPreFactura(string pVisita, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerPreFactura", new object[] {
                        pVisita}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndObtenerPreFactura(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://200.56.177.82/ServicioOA/ObtenerBalance", RequestNamespace="http://200.56.177.82/ServicioOA/", ResponseNamespace="http://200.56.177.82/ServicioOA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerBalance(string pVisita) {
            object[] results = this.Invoke("ObtenerBalance", new object[] {
                        pVisita});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginObtenerBalance(string pVisita, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerBalance", new object[] {
                        pVisita}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndObtenerBalance(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://200.56.177.82/ServicioOA/AgregarConteos", RequestNamespace="http://200.56.177.82/ServicioOA/", ResponseNamespace="http://200.56.177.82/ServicioOA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AgregarConteos(System.Data.DataSet dsProductos) {
            object[] results = this.Invoke("AgregarConteos", new object[] {
                        dsProductos});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAgregarConteos(System.Data.DataSet dsProductos, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AgregarConteos", new object[] {
                        dsProductos}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndAgregarConteos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
}
